"""
Django settings for quantumcrypto project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'staticfiles/'
# Place to collect all static file for nginx to serve as static/
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='0123456789')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'bb84',
    'e91',
    'shared',
    'dps',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'quantumcrypto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = "quantumcrypto.asgi.application"

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation'
                '.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation'
                '.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation'
                '.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation'
                '.NumericPasswordValidator',
    },
]

CHANNEL_LAYERS = {
    'default': {
        ### Method 1: Via redis lab
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {
        #     "hosts": [
        #       'redis://h:<password>;@<redis Endpoint>:<port>' 
        #     ],
        # },

        ### Method 2: Via local Redis  <<< THIS IS THE ACTIVE METHOD >>>
        ## Requires Redis reachable at 127.0.0.1:6379 — start it with:
        ##     docker run --rm -p 6379:6379 -d redis:5
        ## Note: '127.0.0.1' is correct when Django runs on the HOST (local dev and
        ## the server install, where redis.service publishes the port to the host).
        ## It does NOT work under docker-compose, where Django runs in a container
        ## and Redis is a separate container reachable at the hostname 'redis'.
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },

        ### Method 3: Via In-memory channel layer
        ## NOT used (kept for reference). Needs no Redis, but only works within a
        ## single process, so it cannot back a multi-process deployment.
        # "BACKEND": "channels.layers.InMemoryChannelLayer"
    },
}

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
# LANGUAGE_CODE = 'fr-ca'
os.environ.update({'LANGUAGE_CODE': LANGUAGE_CODE})

TIME_ZONE = 'America/Montreal'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SESSION_COOKIE_SECURE = True #Décommenté une fois qu'on a un bon
# certificat ssl
# CSRF_COOKIE_SECURE = True #idem
# CSRF_TRUSTED_ORIGINS: Liste des origines autorisées pour les requêtes CSRF
# On ajoute les domaines du frontend AWS Amplify pour permettre les requêtes POST/PUT/DELETE
CSRF_TRUSTED_ORIGINS = ['https://bb84.physique.usherbrooke.ca',
                        'http://localhost:3000',
                        'https://quantumcrypto.app',
                        'https://www.quantumcrypto.app',
                        'https://www.cryptoquantique.app',
                        'https://cryptoquantique.app',
                        'https://prod.d336iokz5kgpku.amplifyapp.com']  # URL temporaire pour tests

ALLOWED_HOSTS = ["bb84.physique.usherbrooke.ca", "127.0.0.1", 'localhost', "django"]

LOGGING_CONF = {'debug': {'level': 'DEBUG', 'filename': 'debug.log'},
                'error': {'level': 'ERROR', 'filename': 'error.log'},
                'critical': {'level': 'CRITICAL', 'filename': 'critical.log'}}
CURRENT_LOG_LEVEL = 'debug'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': LOGGING_CONF[CURRENT_LOG_LEVEL]['level'],
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / LOGGING_CONF[CURRENT_LOG_LEVEL]['filename'],
        },
        'null': {
            'level': 'DEBUG',
            'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'channels': {
            'handlers': ['null'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['null'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

CORS_ORIGIN_ALLOW_ALL = True

# CORS_ALLOW_PRIVATE_NETWORK: Requis depuis Chrome 104+ (2022)
# Chrome considère bb84.physique.usherbrooke.ca comme un réseau "privé/inconnu"
# car c'est un serveur universitaire (pas sur le cloud public).
# Sans cette option, Chrome bloque les requêtes du frontend AWS vers notre backend.
# Voir: https://developer.chrome.com/blog/private-network-access-update/
CORS_ALLOW_PRIVATE_NETWORK = True


REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    # ]
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}
